### ISSUE TITLE
White Screen after Backup

### ISSUE THREAD

**Issue by kgollmer** [do-while/contao-BackupDB#19]
Hey there, when I press any of the buttons, it loads to a white screen - nothing else happens and there are no files to be found. This problem occurs since I updated to contao 4.9.5, it worked before with my installation.

**Comment by do-while** [comment]
I can't understand this, it works perfectly for me.
Can it be a rights problem?

On which PHP version does the installation run?
How are the settings configured?
How long does it take to display the white page?

**Comment by kgollmer** [comment]
The error-log entry says, it's an "Out of memory"-problem (weird because it used to work).
It takes about 5 to 10 seconds, and I've tried reinstalling, standard-settings and using a different backup-folder.
PHP Version is 7.3.22 , Contao-Version is now 4.10
Since it last worked, I didn't install any new modules, just removed some (hence the re-install).

This is the error: 
[2020-09-09 08:42:08] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\OutOfMemoryError: "Error: Out of memory (allocated 707936256) (tried to allocate 20480 bytes)" at /vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Result.php line 208 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Error: Out of memory (allocated 707936256) (tried to allocate 20480 bytes) at /vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Result.php:208)"} []

Here is an info: 
request.INFO: Matched route "contao_backend". 

and here is information from debug: 
User Deprecated: The "Softleister\BackupDbBundle\Controller\BackupDbController" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.

**Comment by do-while** [comment]
Out-Of-Memory is not enough memory, this is a problem of the hosting settings.

It may be, that some updated modules needs more memory than before.
Do you have entries in the blacklist? "tl_lock, tl_log, tl_search, tl_search_index, tl_session, tl_undo, tl_version" is a good idea, because you don't necessarily need this data at restore.
Even without new modules the memory requirement can grow, e.g. if there are more or larger sessions or more entries in the search index.

I add the deprecated message on my todo list, but this is only a warning and has nothing to do with the error.
